#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
F1TENTH Simulation Pipeline Setup
==================================
맵 파일과 레이스라인을 받아서 시뮬레이션 환경을 구성합니다.

사용법:
  # 이미 변환된 raceline CSV (x_m, y_m, heading, v_mps 포함)
  python3 scripts/setup_simulation.py \\
      --map_yaml /path/to/Budapest_map.yaml \\
      --raceline /path/to/Budapest_optimal_rl.csv

  # 원시 trajectory 파일 (traj_race_cl_00.csv 형식) — --traj 플래그 추가
  python3 scripts/setup_simulation.py \\
      --map_yaml /path/to/Budapest_map.yaml \\
      --raceline /path/to/traj_race_cl_00.csv --traj \\
      --map_name Budapest

  # 스폰 위치 수동 지정
  python3 scripts/setup_simulation.py \\
      --map_yaml /path/to/map.yaml \\
      --raceline /path/to/raceline.csv \\
      --spawn_x 16.0 --spawn_y 98.0 --spawn_theta 3.33

파이프라인:
  1. 맵 .yaml + 이미지(.png/.pgm) → <package>/maps/ 복사
  2. 레이스라인 → (변환 필요 시 convert_traj_to_raceline.py 실행) → <package>/racelines/ 복사
  3. raceline row 0 에서 스폰 위치 읽기 (또는 --spawn_* 인수 사용)
  4. <package>/config/simulation.yaml 업데이트
  5. f1tenth_gym_ros/config/sim_<map_name>.yaml 생성 (gym_bridge 직접 사용 가능)
  6. install share 에도 동기화 (colcon build 없이 즉시 사용 가능)
"""

import argparse
import csv
import os
import shutil
import subprocess
import sys

import yaml

# 스크립트 위치로부터 패키지 루트 결정
SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
PKG_ROOT = os.path.dirname(SCRIPTS_DIR)                   # src/pp_adaptive
PKG_NAME = os.path.basename(PKG_ROOT)                     # pp_adaptive
MAPS_DIR = os.path.join(PKG_ROOT, "maps")
RACELINES_DIR = os.path.join(PKG_ROOT, "racelines")
CONFIG_DIR = os.path.join(PKG_ROOT, "config")
SIM_CONFIG = os.path.join(CONFIG_DIR, "simulation.yaml")
CONVERT_SCRIPT = os.path.join(SCRIPTS_DIR, "convert_traj_to_raceline.py")

# 워크스페이스 루트 (src/ 의 부모)
WS_ROOT = os.path.dirname(os.path.dirname(PKG_ROOT))                   # sim_ws/
INSTALL_SHARE = os.path.join(WS_ROOT, "install", PKG_NAME, "share", PKG_NAME)
GYM_CONFIG_DIR = os.path.join(WS_ROOT, "src", "f1tenth_gym_ros", "config")


# ─────────────────────────────────────────────
# 헬퍼 함수
# ─────────────────────────────────────────────

def find_image_next_to_yaml(yaml_path: str) -> str:
    """map yaml 옆에 있는 이미지 파일(.png / .pgm / .jpg) 경로 반환"""
    base = os.path.splitext(yaml_path)[0]
    for ext in [".png", ".pgm", ".jpg", ".jpeg"]:
        if os.path.exists(base + ext):
            return base + ext
    # yaml 내부의 image: 필드에서 읽기
    try:
        with open(yaml_path) as f:
            data = yaml.safe_load(f)
        img_field = data.get("image", "")
        if img_field:
            candidate = os.path.join(os.path.dirname(yaml_path), img_field)
            if os.path.exists(candidate):
                return candidate
    except Exception:
        pass
    return ""


def read_spawn_from_raceline(raceline_path: str):
    """raceline CSV 첫 번째 데이터 행에서 (x, y, heading) 읽기"""
    with open(raceline_path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            x = float(row.get("x_m", 0.0))
            y = float(row.get("y_m", 0.0))
            # heading / theta_rad / stheta 중 첫 번째로 있는 것 사용
            theta = float(
                row.get("heading") or row.get("theta_rad") or row.get("stheta") or 0.0
            )
            return x, y, theta
    return 0.0, 0.0, 0.0


def read_map_properties(map_yaml_path: str) -> dict:
    """map yaml에서 resolution, origin, image 등 속성 읽기"""
    try:
        with open(map_yaml_path) as f:
            data = yaml.safe_load(f)
        return data or {}
    except Exception:
        return {}


def write_gym_sim_config(
    map_name: str,
    map_yaml_dst: str,
    map_img_src: str,
    sx: float,
    sy: float,
    stheta: float,
    max_laps: int,
) -> str:
    """f1tenth_gym_ros/config/sim_<map_name>.yaml 생성 후 경로 반환"""
    if not os.path.isdir(GYM_CONFIG_DIR):
        print(f"[WARN] f1tenth_gym_ros config 폴더를 찾을 수 없습니다: {GYM_CONFIG_DIR}")
        return ""

    # map_path: 확장자 없는 절대 경로 (gym_bridge 규격)
    map_path_no_ext = os.path.splitext(map_yaml_dst)[0]

    # 이미지 확장자 결정 (.png / .pgm)
    map_props = read_map_properties(map_yaml_dst)
    img_field = map_props.get("image", "")
    img_ext = os.path.splitext(img_field)[1] if img_field else (
        os.path.splitext(map_img_src)[1] if map_img_src else ".png"
    )

    # 맵 해상도/원점 주석용
    resolution = map_props.get("resolution", "N/A")
    origin     = map_props.get("origin", "N/A")

    content = f"""\
# f1tenth_gym_ros sim config — auto-generated by setup_simulation.py
# map:       {map_name}
# resolution:{resolution}
# origin:    {origin}
bridge:
  ros__parameters:
    # topics and namespaces
    ego_namespace: 'ego_racecar'
    ego_scan_topic: 'scan'
    ego_odom_topic: 'odom'
    ego_opp_odom_topic: 'opp_odom'
    ego_drive_topic: 'drive'
    opp_namespace: 'opp_racecar'
    opp_scan_topic: 'opp_scan'
    opp_odom_topic: 'odom'
    opp_ego_odom_topic: 'opp_odom'
    opp_drive_topic: 'opp_drive'

    # transform related
    scan_distance_to_base_link: 0.275

    # laserscan parameters
    scan_fov: 4.7
    scan_beams: 1080

    # map parameters
    map_path: '{map_path_no_ext}'
    map_img_ext: '{img_ext}'

    # opponent parameters
    num_agent: 1
    max_laps: {max_laps}  # 0 = unlimited

    # ego starting pose (from raceline row 0)
    sx: {sx}
    sy: {sy}
    stheta: {stheta}

    # opp starting pose
    sx1: 2.0
    sy1: 0.5
    stheta1: 0.0

    # misc
    kb_teleop: False
    debug_lookahead_m: -1.0
    train_rl: False
"""
    out_path = os.path.join(GYM_CONFIG_DIR, f"sim_{map_name}.yaml")
    with open(out_path, "w") as f:
        f.write(content)
    return out_path


def sync_to_install(src_file: str, subdir: str):
    """install/share 디렉터리로 파일 동기화 (존재할 때만)"""
    dst_dir = os.path.join(INSTALL_SHARE, subdir)
    if os.path.isdir(dst_dir):
        dst_file = os.path.join(dst_dir, os.path.basename(src_file))
        # symlink-install 환경에서는 src/dst가 동일 파일일 수 있다.
        try:
            if os.path.exists(dst_file) and os.path.samefile(src_file, dst_file):
                return dst_file
        except OSError:
            pass
        shutil.copy2(src_file, dst_file)
        return dst_file
    return None


# ─────────────────────────────────────────────
# 메인 파이프라인
# ─────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description="F1TENTH 시뮬레이션 파이프라인 설정",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    ap.add_argument("--map_yaml", required=True,
                    help="맵 YAML 파일 경로 (옆에 이미지 파일이 있어야 함)")
    ap.add_argument("--raceline", required=True,
                    help="레이스라인 CSV 파일 경로")
    ap.add_argument("--traj", action="store_true",
                    help="입력이 raw trajectory 형식 (traj_race_cl_00.csv). "
                         "convert_traj_to_raceline.py 로 변환 후 저장")
    ap.add_argument("--map_name",
                    help="맵 이름 (미입력 시 yaml 파일명에서 자동 결정)")
    ap.add_argument("--raceline_name",
                    help="저장할 레이스라인 파일명 (미입력 시 자동 결정)")
    ap.add_argument("--spawn_x", type=float, default=None,
                    help="시작 x 좌표 (미입력 시 raceline row 0에서 읽음)")
    ap.add_argument("--spawn_y", type=float, default=None,
                    help="시작 y 좌표")
    ap.add_argument("--spawn_theta", type=float, default=None,
                    help="시작 각도 [rad]")
    ap.add_argument("--max_laps", type=int, default=3,
                    help="목표 완주 랩 수 (default: 3, 0=무제한)")
    ap.add_argument("--rviz", action="store_true", default=True,
                    help="RViz 활성화 (default: True)")
    ap.add_argument("--no_rviz", action="store_true",
                    help="RViz 비활성화")
    args = ap.parse_args()

    rviz_on = not args.no_rviz

    # ── Step 1: 맵 파일 복사 ──────────────────────────────────────
    map_yaml_src = os.path.abspath(args.map_yaml)
    if not os.path.exists(map_yaml_src):
        print(f"[ERROR] 맵 YAML 파일을 찾을 수 없습니다: {map_yaml_src}")
        sys.exit(1)

    map_name = args.map_name or os.path.splitext(os.path.basename(map_yaml_src))[0]
    map_img_src = find_image_next_to_yaml(map_yaml_src)

    os.makedirs(MAPS_DIR, exist_ok=True)
    map_yaml_dst = os.path.join(MAPS_DIR, os.path.basename(map_yaml_src))
    if os.path.abspath(map_yaml_src) != os.path.abspath(map_yaml_dst):
        shutil.copy2(map_yaml_src, map_yaml_dst)
        print(f"[1/5] 맵 YAML 복사: {map_yaml_dst}")
    else:
        print(f"[1/5] 맵 YAML 이미 존재 (스킵): {map_yaml_dst}")

    if map_img_src:
        map_img_dst = os.path.join(MAPS_DIR, os.path.basename(map_img_src))
        if os.path.abspath(map_img_src) != os.path.abspath(map_img_dst):
            shutil.copy2(map_img_src, map_img_dst)
            print(f"[1/5] 맵 이미지 복사: {map_img_dst}")
        else:
            print(f"[1/5] 맵 이미지 이미 존재 (스킵): {map_img_dst}")
    else:
        print(f"[WARN] 맵 이미지 파일을 찾지 못했습니다 (yaml 옆에 .png/.pgm 필요)")

    # install/share/maps 에도 동기화
    sync_to_install(map_yaml_dst, "maps")
    if map_img_src:
        sync_to_install(map_img_dst, "maps")

    # ── Step 2: 레이스라인 변환 / 복사 ───────────────────────────
    raceline_src = os.path.abspath(args.raceline)
    if not os.path.exists(raceline_src):
        print(f"[ERROR] 레이스라인 파일을 찾을 수 없습니다: {raceline_src}")
        sys.exit(1)

    os.makedirs(RACELINES_DIR, exist_ok=True)

    if args.traj:
        # raw trajectory → raceline 변환
        if args.raceline_name:
            out_name = args.raceline_name
        else:
            out_name = f"{map_name}_optimal_rl.csv"
        raceline_dst = os.path.join(RACELINES_DIR, out_name)

        print(f"[2/5] Trajectory 변환 중: {os.path.basename(raceline_src)} → {out_name}")
        cmd = [
            sys.executable, CONVERT_SCRIPT,
            "--input", raceline_src,
            "--name", map_name,
            "--out_dir", RACELINES_DIR,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"[ERROR] convert_traj_to_raceline.py 실패:")
            print(result.stderr)
            sys.exit(1)
        print(result.stdout.strip())
        # convert 스크립트가 <map_name>_optimal_rl.csv 로 저장함
        raceline_dst = os.path.join(RACELINES_DIR, f"{map_name}_optimal_rl.csv")
    else:
        # 이미 raceline 형식 — 그대로 복사
        if args.raceline_name:
            out_name = args.raceline_name
        else:
            out_name = os.path.basename(raceline_src)
        raceline_dst = os.path.join(RACELINES_DIR, out_name)
        if os.path.abspath(raceline_src) != os.path.abspath(raceline_dst):
            shutil.copy2(raceline_src, raceline_dst)
        print(f"[2/5] 레이스라인 복사: {raceline_dst}")

    sync_to_install(raceline_dst, "racelines")

    # ── Step 3: 스폰 위치 결정 ────────────────────────────────────
    if args.spawn_x is not None and args.spawn_y is not None and args.spawn_theta is not None:
        sx, sy, stheta = args.spawn_x, args.spawn_y, args.spawn_theta
        print(f"[3/5] 스폰 위치 (수동): x={sx}, y={sy}, θ={stheta:.4f} rad")
    else:
        sx, sy, stheta = read_spawn_from_raceline(raceline_dst)
        print(f"[3/5] 스폰 위치 (raceline row 0): x={sx}, y={sy}, θ={stheta:.4f} rad")

    # ── Step 4: simulation.yaml 업데이트 ─────────────────────────
    raceline_file = os.path.basename(raceline_dst)

    sim_config_data = {
        "simulation": {
            "map_name": map_name,
            "raceline_file": raceline_file,
            "spawn_x": round(sx, 6),
            "spawn_y": round(sy, 6),
            "spawn_theta": round(stheta, 6),
            "max_laps": args.max_laps,
            "num_agent": 1,
            "rviz": rviz_on,
            "lookahead_fallback": None,
            "a_lat_max": None,
            "slowdown_gain": None,
            "v_floor": None,
        }
    }

    os.makedirs(CONFIG_DIR, exist_ok=True)
    with open(SIM_CONFIG, "w") as f:
        yaml.dump(sim_config_data, f, default_flow_style=False, allow_unicode=True,
                  sort_keys=False)
    print(f"[4/5] simulation.yaml 업데이트: {SIM_CONFIG}")
    sync_to_install(SIM_CONFIG, "config")

    # ── Step 5: f1tenth_gym_ros/config/sim_<map_name>.yaml 생성 ──
    gym_cfg_path = write_gym_sim_config(
        map_name=map_name,
        map_yaml_dst=map_yaml_dst,
        map_img_src=map_img_src,
        sx=sx,
        sy=sy,
        stheta=stheta,
        max_laps=args.max_laps,
    )
    if gym_cfg_path:
        print(f"[5/5] gym sim config 생성: {gym_cfg_path}")
    else:
        print(f"[5/5] gym sim config 생성 스킵 (f1tenth_gym_ros 없음)")

    # ── 완료 출력 ─────────────────────────────────────────────────
    print()
    print("=" * 60)
    print("설정 완료!")
    print(f"  맵:        {map_name}")
    print(f"  레이스라인: {raceline_file}")
    print(f"  스폰:      ({sx:.3f}, {sy:.3f}) θ={stheta:.3f} rad")
    print()
    print("시뮬레이션 실행:")
    print("  # RViz 포함 (기본)")
    print("  ros2 launch pp_adaptive pp_adaptive_sim_launch.py")
    print()
    print("  # RViz 없이")
    print("  ros2 launch pp_adaptive pp_adaptive_sim_launch.py rviz:=false")
    print("=" * 60)


if __name__ == "__main__":
    main()
